import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Get started',
      link: { type: 'doc', id: 'get-started/introduction' },
      items: [{ type: 'autogenerated', dirName: 'get-started' }],
    },
    {
      type: 'category',
      label: 'Install and setup',
      link: { type: 'doc', id: 'install-and-setup/manual' },
      items: [{ type: 'autogenerated', dirName: 'install-and-setup' }],
    },
    {
      type: 'category',
      label: 'FHIR',
      link: { type: 'doc', id: 'fhir/guides/overview-of-fhir' },
      items: [{ type: 'autogenerated', dirName: 'fhir' }],
    },
    {
      type: 'category',
      label: 'HL7',
      link: { type: 'doc', id: 'hl7/guides/overview' },
      items: [{ type: 'autogenerated', dirName: 'hl7' }],
    },
    {
      type: 'category',
      label: 'Data Transformation',
      link: { type: 'doc', id: 'data-transformation/guides/hl7v2-fhir' },
      items: [{ type: 'autogenerated', dirName: 'data-transformation' }],
    },
    {
      type: 'category',
      label: 'EMR Connectivity',
      link: { type: 'doc', id: 'emr-connectivity/guides/emr-systems-overview' },
      items: [{ type: 'autogenerated', dirName: 'emr-connectivity' }],
    },
    {
      type: 'category',
      label: 'Secure Health APIs',
      link: { type: 'doc', id: 'secure-health-apis/guides/smart-on-fhir-overview' },
      items: [{ type: 'autogenerated', dirName: 'secure-health-apis' }],
    },
    {
      type: 'category',
      label: 'Advanced Topics',
      link: { type: 'doc', id: 'advance-topics/guides/enable-workflow' },
      items: [{ type: 'autogenerated', dirName: 'advance-topics' }],
    },
    {
      type: 'category',
      label: 'Other',
      items: [
        { type: 'autogenerated', dirName: 'concepts' },
        { type: 'autogenerated', dirName: 'configurations' },
        { type: 'autogenerated', dirName: 'connectors' },
        { type: 'autogenerated', dirName: 'resources' },
        { type: 'autogenerated', dirName: 'use-cases' },
        'guides-overview',
        'references-overview',
        'set-up-wso2-integration-studio',
        'smart-specification',
        'page-not-found',
      ],
    },
  ],
};

export default sidebars;
